name: Atualizar dados do gateway

on:
  schedule:
    - cron: '0 12 * * *'  # Executa todo dia às 12h UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GATEWAY_USERNAME: ${{ secrets.GATEWAY_USERNAME }}
      GATEWAY_PASSWORD: ${{ secrets.GATEWAY_PASSWORD }}

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Criar secrets.toml
        run: |
          mkdir -p ~/.streamlit
          echo "GATEWAY_USERNAME = '${{ secrets.GATEWAY_USERNAME }}'" > ~/.streamlit/secrets.toml
          echo "GATEWAY_PASSWORD = '${{ secrets.GATEWAY_PASSWORD }}'" >> ~/.streamlit/secrets.toml

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências (sem cache)
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Executar script de atualização
        run: python update_data.py
